sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: ZDc2HTpYvuFpNK6FtKdEwYJZ476WFvP4O4NECWMDtbUNhzerUWfx5nyawHWQbsXMBL/iiSBOjDnbJ/8tOUH1wSZJXu5QZrRS7dedoIqF9d4af9DHyPcoTn4EiCjLx4mBrjBY+wxFz5IqDavbPlwdUVFT+ecZRKVPgI07DhvDxRQ+EDbHLTB6qFGcdjrkOjuGkHRsNIG8SypQ+KMfltYXEuET4qd4+lOsiT8Re4KpyB+S//2mgb51CyJwHL1y3eTtgydXHZENzNI+BSVcy4GAw0BBh9SaHgfPeW5gb9BnVaS6o2+yXSm1DQIqq/l+SPDXsREBvZIp/paQhm+uA+Jy7RIqPbuDBiM6Qp+5tZMBOL4d8qdFoluU5N4T7f7uqmcYDJ5ADbtxmmDrG2Mi2i/Vak4/2TzwGVjq4wjkf/osomHAqrz9YL9hrTc5t7vb/3kOymqEYqHZt/fIm+Mcjk0GtEtbaUzb+R9nxyfycqh6ji8Cy+wjPk1FLHONzIPLTDmtd+vmY4ytZMGmopIjDb8brRypWr1qeTEgeuoTez//3dE4LpsJVSaGZ7P4jFsUKHLyfrwPQ6LbYUwyLQu1TRL9s9I3U639Aavc+0PPFNorlGlMnt62n6P0rin1v4tjKOw+54yzTImx3C2e2IPi9MsFRYYKxIBCr2FC8qQpQjP2xn4=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Founder-of-New-France---A-Chronicle-of-Champlain_4213
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy